import "reflect-metadata";
import dotenv from "dotenv";
import { DataSource } from "typeorm";

import {
  MarketListing,
  ResourceGroup,
  NftAddress,
  NftType,
  Collection,
  Seller,
  Uri,
  Animation,
  Youtube,
  Description,
  ThirdPartyTransaction,
  StripeRateLimit,
  PaperPaymentId,
  TransactionLog,
  MarketListingGrouped,
  TransactionStatus,
  TransactionType,
  Calendar,
  Init,
  MarketListingNotGrouped,
  Audio,
  DashboardQueue,
  RefundIce,
  // RawTransaction,
  RawResourceData,
  User,
  CollectionMetadata,
  Media,
  CollectionMediaAccess,
  CollectionMedia,
  CollectionsRevelableContent,
  Message,
  Conversation,
  ConversationParticipants,
} from "./entity/index";

dotenv.config();
// import { initialMigration1671650744593 } from "./migrations/1671650744593-initial-migration";
// import { transactionLogAnalitycs1671822450958 } from "./migrations/1671822450958-transaction-log-analitycs";
const {
  MYSQL_USER,
  MYSQL_HOST,
  MYSQL_DATABASE,
  MYSQL_PASSWORD,
  DB_DIALECT,
  MYSQL_PORT,
  DB_SYNC,
  DB_LOG,
  MONGO_URL,
  MONGO_DB,
} = process.env;

export const AppDataSource = new DataSource({
  type: DB_DIALECT as "mysql",
  host: MYSQL_HOST,
  port: parseInt(MYSQL_PORT || "3306"),
  username: MYSQL_USER,
  password: MYSQL_PASSWORD,
  database: `${MYSQL_DATABASE}`,
  synchronize: DB_SYNC === "true",
  logging: DB_LOG === "true",
  // migrationsRun: true,
  maxQueryExecutionTime: 20000,
  entities: [
    MarketListing,
    ResourceGroup,
    NftAddress,
    NftType,
    Collection,
    Seller,
    Uri,
    Animation,
    Youtube,
    Description,
    ThirdPartyTransaction,
    StripeRateLimit,
    PaperPaymentId,
    TransactionLog,
    MarketListingGrouped,
    TransactionStatus,
    TransactionType,
    Calendar,
    Init,
    MarketListingNotGrouped,
    Audio,
    DashboardQueue,
    RefundIce,
    // RawTransaction,
    RawResourceData,
    User,
    Media,
    CollectionsRevelableContent,
    Message,
    Conversation,
    ConversationParticipants,
  ],
  migrations: [
    // initialMigration1671650744593,
    // transactionLogAnalitycs1671822450958,
  ],
  subscribers: [],
});
export const MongoDataSource = new DataSource({
  name: "MongoDataSource",
  type: "mongodb" as "mongodb",
  url: MONGO_URL,
  synchronize: true,
  logging: DB_LOG === "true",
  useUnifiedTopology: true,
  useNewUrlParser: true,
  entities: [CollectionMetadata, CollectionMedia, CollectionMediaAccess],
  subscribers: [],
});
